name: "Global Autograder"
author: "Arthur Carvalho"
description: "An autograding tool for GitHub Classroom. Flexible,extensive configuration with consistent scoring and a feedback report placed directly in student's repository"

# Defines the inputs that the action can receive.
# These are mapped to the arguments in the `runs` section below.
inputs:
  github-token:
    description: >
      GitHub token for API access. Defaults to the token provided by GitHub Actions.
    required: false
    default: ${{ github.token }}
  template_preset:
    description: 'Defines the set of grading rules and point values to apply. To create your own grading preset, use "custom".'
    required: true
  feedback-type:
    description: 'The type or style of feedback to provide to the student (e.g., summary, detailed).'
    required: true
  custom_template:
    description: 'Optional custom grading template in JSON format. Required if template_preset is set to "custom".'
    required: false
  openai_key:
    description: 'Optional OpenAI API key for generating AI-assisted feedback.'
    required: false
  redis_url:
    description: 'Optional URL for a Redis instance for caching.'
    required: false
  redis_token:
    description: 'Optional authentication token for the Redis instance.'
    required: false
  app_token:
    description: 'The application token for the autograder service.'
    required: false

# Defines the output variable of the action.
outputs:
  result:
    description: "Base64-encoded JSON containing the results of the grading."

# Configures how the action is executed.
runs:
  using: docker
  image: "Dockerfile"
  # Use 'env' to pass named variables to the container
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    APP_TOKEN: ${{ inputs.app_token }}
    CUSTOM_TEMPLATE: ${{ inputs.custom_template }}
    TEMPLATE_PRESET: ${{ inputs.template_preset }}
    FEEDBACK_TYPE: ${{ inputs.feedback-type }}
    OPENAI_KEY: ${{ inputs.openai_key }}
    REDIS_URL: ${{ inputs.redis_url }}
    REDIS_TOKEN: ${{ inputs.redis_token }}
