name: "HTML/CSS/JS Autograder"
author: "Webtech Network"
description: "An autograding tool for GitHub Classroom that evaluates students' HTML, CSS, and JavaScript projects."
inputs:
  token:
    description: >
      GitHub token used to check repository content and provide feedback. By default, 
      this uses the repository token provided by GitHub Actions. You can customize this
      by replacing this token with a user token which has write-access to your repository. 
      Note that the token will be accessible to all repository collaborators.
    default: ${{ github.token }} #This is the only way to obtain a valid github token for API use.
  redis_name:
      description: >
          Redis token used to connect to the Redis server for caching and state management.
          This is optional and can be set if you have a Redis instance running.
  redis_url:
      description: >
          URL of the Redis server to connect to. This is optional and can be set if you have a Redis instance running.
          If not provided, the autograder will run without Redis caching.
  autograder_engine:
      description: >
          The autograder engine to use for grading. This can be set to 'default' or 'custom'.
          If 'custom', you must provide a custom Dockerfile in the repository.
      

outputs:
  result:
    description: "Base64-encoded JSON containing the results of the grading."

runs:
  using: docker
  image: "Dockerfile"  # The Docker image containing the autograder
  args:
    - ${{ inputs.token }}
    - ${{ inputs.redis_name }}
    - ${{ inputs.redis_url }}
    - ${{ inputs.autograder_engine }}
