name: "HTML/CSS/JS Autograder"
author: "Webtech Network"
description: "An autograding tool for GitHub Classroom that evaluates students' HTML, CSS, and JavaScript projects."
inputs:
  JWT_SECRET:
    description: >
      JWT token used to authenticate the autograder. This is required for the autograder to function properly.
      It should be provided by the GitHub Classroom setup.
    required: true
  token:
    description: >
      GitHub token used to check repository content and provide feedback. By default, 
      this uses the repository token provided by GitHub Actions. You can customize this
      by replacing this token with a user token which has write-access to your repository. 
      Note that the token will be accessible to all repository collaborators.
    default: ${{ github.token }} #This is the only way to obtain a valid github token for API usage.
  redis_name:
      description: >
          Redis token used to connect to the Redis server for caching and state management.
          This is optional and can be set if you have a Redis instance running.
  autograder_bot_token:
    description: >
        The token for the autograder bot. This is used to post comments and results back to the repository.
        If not provided, the autograder will run without posting comments.
  redis_url:
      description: >
          URL of the Redis server to connect to. This is optional and can be set if you have a Redis instance running.
          If not provided, the autograder will run without Redis caching.
  autograder_engine:
      description: >
          The autograder engine to use for grading. This can be set to 'default' or 'custom'.
          If 'custom', you must provide a custom Dockerfile in the repository.
      

outputs:
  result:
    description: "Base64-encoded JSON containing the results of the grading."

runs:
  using: docker
  image: "Dockerfile"  # The Docker image containing the autograder
  env:
    JWT_TOKEN: ${{ inputs.JWT_SECRET }}
    GITHUB_TOKEN:  ${{ inputs.token }}
    APP_TOKEN: ${{ inputs.autograder_bot_token }}
    REDIS_TOKEN: ${{ inputs.redis_name }}
    REDIS_URL: ${{ inputs.redis_url }}
    OPENAI_KEY: ${{ inputs.autograder_engine }}
