name: "HTML/CSS/JS Autograder"
author: "Webtech Network"
description: "An autograding tool for GitHub Classroom that evaluates students' HTML, CSS, and JavaScript projects."

# Defines the inputs that the action can receive.
# These are mapped to the arguments in the `runs` section below.
inputs:
  github-token:
    description: >
      GitHub token for API access. Defaults to the token provided by GitHub Actions.
    required: false
    default: ${{ github.token }}
  grading_preset:
    description: 'Defines the set of grading rules and point values to apply.'
    required: true
  feedback-type:
    description: 'The type or style of feedback to provide to the student (e.g., summary, detailed).'
    required: true
  openai_key:
    description: 'Optional OpenAI API key for generating AI-assisted feedback.'
    required: false
  redis_url:
    description: 'Optional URL for a Redis instance for caching.'
    required: false
  redis_token:
    description: 'Optional authentication token for the Redis instance.'
    required: false
  app_token:
    description: 'The application token for the autograder service.'
    required: false
  test_framework:
    description: 'Specifies the test framework to use for grading (e.g., jest, cypress).'
    required: false

# Defines the output variable of the action.
outputs:
  result:
    description: "Base64-encoded JSON containing the results of the grading."

# Configures how the action is executed.
runs:
  using: docker
  image: "Dockerfile"  # Specifies the Docker image to run.
  # Passes the inputs to the container's entrypoint script ($1, $2, etc.).
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.app_token }}
    - ${{ inputs.test_framework }}
    - ${{ inputs.grading_preset }}
    - ${{ inputs.feedback-type }}
    - ${{ inputs.openai_key }}
    - ${{ inputs.redis_url }}
    - ${{ inputs.redis_token }}