services:
  db: 
    image: postgres:17
    entrypoint: 
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pd_isready -U user -d db"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s