name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        echo CI_COMMIT_SHA=${CI_COMMIT_SHA}
        echo CI_MERGE_REQUEST_TARGET_BRANCH_NAME=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
        git fetch origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
        tmp_files=$(git diff --name-only ${CI_COMMIT_SHA} origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME})
        echo "Changed files are $tmp_files"
        if [ -z "$(echo "$tmp_files" | grep "\.py")" ]; then exit 0; else echo "Python files are found"; fi
        tmp_pfiles=$(echo "$tmp_files" | grep "\.py")
        echo "Python files are $tmp_pfiles"
        mkdir ./pylint
        pylint $tmp_pfiles | tee ./pylint/pylint.log || pylint-exit $?
